fix:[CDS-92065]: Pipeline Notifications: Null error when either of us…
harness/harness-schema pull request #342
Opened 2024-03-05 11:47 UTC by Aninditaa-ch

…ergroup or webhook url is removed from notification rule YAML

2024-03-05 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-schema?pullRequest=342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-schema?pullRequest=342) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-schema?pullRequest=342) it.</sub>

2024-03-07 09:48 UTC, rchaudharyy submitted a review, later dismissed
LGTM

2024-03-13 10:36 UTC, shalini-agr approved these changes

2024-03-13 11:04 UTC, sahilhindwani-harness requested changes

2024-03-13 11:04 UTC, sahilhindwani-harness commented on v0/pipeline.json
> +          "required" : [ "userGroups", "recipients" ],
This is wrong, both of these are not required. Why do we need this change?

2024-03-18 09:57 UTC, closed without merging