fix: [PIPE-16799]: Able to save Pipeline without any stage and step
harness/harness-schema pull request #393
Opened 2024-05-24 13:24 UTC by jatin-harness

Ticket Link: https://harness.atlassian.net/browse/PIPE-16799
Issue: Customer could save pipeline without any stages and step
Changes: Making "stages" in the yaml as required field.

2024-05-24 13:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-schema?pullRequest=393) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-schema?pullRequest=393) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-schema?pullRequest=393) it.</sub>

2024-05-24 13:31 UTC, utkarshchoubey-harness approved these changes

2024-05-24 13:36 UTC, utkarshchoubey-harness requested changes

2024-05-24 13:36 UTC, utkarshchoubey-harness commented on v0/pipeline/pipeline.yaml
> +  - stages
run bundler to generate schema

2024-06-07 05:28 UTC, utkarshchoubey-harness approved these changes

2024-06-07 16:18 UTC, rohitk-h approved these changes

2024-06-07 16:21 UTC, merged